apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: {{ smoke_test_pvc }}
    namespace: {{ smoke_test_ns }}
  spec:
    storageClassName: change
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
 
 
- apiVersion: v1
  kind: Pod
  metadata:
    name: {{ smoke_test_pod }}-pvc
    namespace: {{ smoke_test_ns }}
  spec:
    containers:
    - name: www
      image: nginx:alpine
      volumeMounts:
      - name: www-persistent-storage
        mountPath: /usr/share/nginx/html
    volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: {{ smoke_test_pvc }}
