apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1beta1
  kind: KubeDescheduler
  metadata:
    name: cluster
    namespace: openshift-kube-descheduler-operator
  spec:
    deschedulingIntervalSeconds: 120
    logLevel: Normal
    managementState: Managed
    operatorLogLevel: Normal
    profiles:
    - LifecycleAndUtilization
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""