apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/cluster-kube-descheduler-operator.openshift-kube-descheduler-op: ""
    name: cluster-kube-descheduler-operator
    namespace: openshift-kube-descheduler-operator
  spec:
    channel: "4.7"
    installPlanApproval: Automatic
    name: cluster-kube-descheduler-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: clusterkubedescheduleroperator.4.7.0-202105061841.p0
kind: List
metadata:
  resourceVersion: ""
  selfLink: