---
apiVersion: v1
kind: Pod
metadata:
  name: load-change
spec:
  containers:
  - name: more-nodes
    image: busybox
    command: ["sleep",  "300"]
    resources:
      requests:
        memory: 500Mi
        cpu: 300m
  restartPolicy: Never